"""add tokens and queue events

Revision ID: e30907dd6255
Revises: 643f180a29dd
Create Date: 2026-10-01 13:45:05.969075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30907dd6255'
down_revision: Union[str, Sequence[str], None] = '643f180a29dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_sequences',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_token_sequences_service_id_services')),
    sa.PrimaryKeyConstraint('service_id', 'date', name=op.f('pk_token_sequences'))
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_number', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('queue_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('walk_in', 'appointment', name='source', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'called', 'no_response', 'recalled', 'skipped', 'in_service', 'completed', 'missed', 'cancelled', name='status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('priority', sa.Boolean(), nullable=False),
    sa.Column('recall_count', sa.Integer(), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('estimated_wait_min', sa.Integer(), nullable=True),
    sa.Column('counter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_tokens_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['counter_id'], ['counters.id'], name=op.f('fk_tokens_counter_id_counters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_tokens_service_id_services')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens')),
    sa.UniqueConstraint('service_id', 'queue_date', 'token_number', name=op.f('uq_tokens_service_id'))
    )
    op.create_index('ix_tokens_service_day_status', 'tokens', ['service_id', 'queue_date', 'status'], unique=False)
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    op.create_index('uq_tokens_active_user_service_day', 'tokens', ['user_id', 'service_id', 'queue_date'], unique=True, postgresql_where=sa.text("status IN ('waiting', 'called', 'no_response', 'recalled', 'in_service')"))
    op.create_table('queue_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Enum('created', 'called', 'no_response', 'recalled', 'skipped', 'missed', 'started', 'completed', 'cancelled', name='event', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('counter_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counter_id'], ['counters.id'], name=op.f('fk_queue_events_counter_id_counters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('fk_queue_events_token_id_tokens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queue_events'))
    )
    op.create_index(op.f('ix_queue_events_token_id'), 'queue_events', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_events_token_id'), table_name='queue_events')
    op.drop_table('queue_events')
    op.drop_index('uq_tokens_active_user_service_day', table_name='tokens', postgresql_where=sa.text("status IN ('waiting', 'called', 'no_response', 'recalled', 'in_service')"))
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_index('ix_tokens_service_day_status', table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('token_sequences')
    # ### end Alembic commands ###
