"""add appointments

Revision ID: 643f180a29dd
Revises: 8c63ce200dc0
Create Date: 2026-10-01 13:27:09.218097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643f180a29dd'
down_revision: Union[str, Sequence[str], None] = '8c63ce200dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('booked', 'confirmed', 'checked_in', 'waiting', 'in_service', 'completed', 'cancelled', 'missed', 'rescheduled', 'delayed', name='status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counter_id', sa.Integer(), nullable=True),
    sa.Column('rescheduled_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counter_id'], ['counters.id'], name=op.f('fk_appointments_counter_id_counters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['appointments.id'], name=op.f('fk_appointments_rescheduled_from_id_appointments')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_appointments_service_id_services')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_appointments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index('ix_appointments_service_day', 'appointments', ['service_id', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.create_index('uq_appointments_active_user_service_day', 'appointments', ['user_id', 'service_id', 'appointment_date'], unique=True, postgresql_where=sa.text("status IN ('booked', 'confirmed', 'checked_in', 'waiting', 'in_service', 'delayed')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_appointments_active_user_service_day', table_name='appointments', postgresql_where=sa.text("status IN ('booked', 'confirmed', 'checked_in', 'waiting', 'in_service', 'delayed')"))
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_index('ix_appointments_service_day', table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
